enum ResponseCode {
    LOGIN_OKAY = "CHANGE_PASSWORD",
    CHANGE_PASSWORD = "CHANGE_PASSWORD",
    REGISTER_OKAY = "REGISTER_OKAY",
    INVALID_TOKEN = "INVALID_TOKEN",
    LOGOUT_OKAY = "LOGOUT_OKAY",
    EMAIL_TAKEN = "EMAIL_TAKEN",
    USERNAME_TAKEN = "USERNAME_TAKEN",
    WRONG_CREDENTIALS = "WRONG_CREDENTIALS",
    NOT_ENOUGH_PARAMETERS = "NOT_ENOUGH_PARAMETERS",
    WRONG_EMAIL_FORMAT = "WRONG_EMAIL_FORMAT",
    PASSWORDS_NOT_MATCHING = "PASSWORDS_NOT_MATCHING",
    ME_OKAY = "ME_OKAY",
    NOT_ENOUGH_PERMISSIONS = "NOT_ENOUGH_PERMISSIONS",
    RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND",
}

export default ResponseCode;